package com.plcoding.contactscomposemultiplatform.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val DarkColorScheme = darkColorScheme(
    primary = RedPrimaryDark,
    secondary = RedSecondaryDark,
    tertiary = RedTertiaryDark,
    onPrimary = OnRedDark,
    primaryContainer = RedContainerDark,
    onPrimaryContainer = OnRedContainerDark,
    onSecondary = OnRedSecondaryDark,
    secondaryContainer = RedSecondaryContainerDark,
    onSecondaryContainer = OnRedSecondaryContainerDark,
    onTertiary = OnRedTertiaryDark,
    onTertiaryContainer = OnRedTertiaryContainerDark,
    tertiaryContainer = RedTertiaryContainerDark,
    background = BackgroundDark,
    onBackground = OnBackgroundDark,
    surface = SurfaceDark,
    onSurface = OnSurfaceDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    outline = OutlineDark,
)

val LightColorScheme = lightColorScheme(
    primary = RedPrimaryLight,
    secondary = RedSecondaryLight,
    tertiary = RedTertiaryLight,
    onPrimary = OnRedLight,
    primaryContainer = RedContainerLight,
    onPrimaryContainer = OnRedContainerLight,
    onSecondary = OnRedSecondaryLight,
    secondaryContainer = RedSecondaryContainerLight,
    onSecondaryContainer = OnRedSecondaryContainerLight,
    onTertiary = OnRedTertiaryLight,
    onTertiaryContainer = OnRedTertiaryContainerLight,
    tertiaryContainer = RedTertiaryContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    outline = OutlineLight,
)